owner: freelance-jp
repo: upptime
user-agent: ogaty

sites:
  - name: www
    url: https://www.freelance-jp.org/
  - name: blog
    url: https://blog.freelance-jp.org/
assignees:
  - keizo3
  - ogaty

status-website:
  baseUrl: /upptime
  name: freelancejp-upptime  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: www
      href: https://www.freelance-jp.org/
    - title: blog
      href: https://blog.freelance-jp.org/

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
